### ISSUE TITLE
Fix smtppass invisible attribute

### ISSUE THREAD

**Issue by ecarreras** [gisce/poweremail#157]
@egarciadiaz és un bug de com es defeneixen els camps i que el gtk no fa cas del "invisible" quan és un password.

Fa un temps ja es va haver de solucionar el problema amb el mòdul `base` i `base_crypt` https://github.com/gisce/erp/pull/14665

S'hauria de fer la mateixa pull-request al poweremail.

_Originally posted by @ecarreras in https://github.com/gisce/webclient/issues/1039#issuecomment-2165395297_

**Comment by egarciadiaz** [comment]
Corregido comportamiento del campo.
